name: ci/build

on:
  push:
    branches:
      - build
      - master
  schedule:
    - cron: '53 1 6,16,26 * *'

jobs:
  vagrant-build:
    name: vagrant-${{ matrix.tag }}
    runs-on: ubuntu-latest
    container: potyarkin/cirrus-run
    strategy:
      matrix:
        tag:
          - debian10
          - debian11
          - debian12
    env:
      CIRRUS_API_TOKEN: ${{ secrets.CIRRUS_API_TOKEN }}
      CIRRUS_GITHUB_REPO: sio/.cirrus-ci-jobs
      CIRRUS_SHOW_BUILD_LOG: always
      ACTION: ${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v1
      - run: cirrus-run .ci/cirrus.yml.j2
